services:
    Alpixel\Bundle\IntegrationBundle\DataCollector\ScreenInfoCollector:
        public: false
        autowire: true
        tags:
            -
                name:     data_collector
                template: 'AlpixelIntegrationBundle::screen_infos.html.twig'
                id:       'alpixel.data_collector.integration.screen_infos'

    Alpixel\Bundle\IntegrationBundle\DataCollector\IntegrationRoutingCollector:
        public: false
        autowire: true
        tags:
            -
                name:     data_collector
                template: 'AlpixelIntegrationBundle::routing.html.twig'
                id:       'alpixel.data_collector.integration.routing'
